### ISSUE TITLE
[BUG Report]-[Plugin] Dictionary definitions include xref tags

### ISSUE THREAD

**Issue by tayjaybabee** [Inspyre-Technologies/EveIRC#113]
**Describe the bug**
When using the dictionrary plugin to define a word the result returns with a bunch of \<xref\> tags. 

**To Reproduce**
1. On IRC type '!define \<word\>' in a channel EveIRC is in (if the dictionary plugin is enabled)

**Expected behavior**
The plugin should be programmed to strip that junk data out as xref tags are useless on IRC

**Screenshots**
![DeepinScreenshot_20190824142626](https://user-images.githubusercontent.com/43686206/63641895-66d4a600-c67b-11e9-820f-5e88292910c1.png)

**Comment by doubledave** [comment]
Changes:
  lib/plugins/dictionary.rb
    67fd699c3e4a9c55a679144891349b8993ef63c2
    1c00d768a0e1c6ba1ee8f6b7e0fc2a4aa803d0ff
In review by @tayjaybabee
